/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _STRUCTURES_H_RPCGEN
#define _STRUCTURES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct update_variables {
	int update_available;
	int update_in_progress;
	int updated_from;
	int old_version_pid;
};
typedef struct update_variables update_variables;

struct container {
	char *name;
	float num_executions;
};
typedef struct container container;

struct container_2 {
	char *name;
	int num_executions;
};
typedef struct container_2 container_2;

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_update_variables (XDR *, update_variables*);
extern  bool_t xdr_container (XDR *, container*);
extern  bool_t xdr_container_2 (XDR *, container_2*);

#else /* K&R C */
extern bool_t xdr_update_variables ();
extern bool_t xdr_container ();
extern bool_t xdr_container_2 ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_STRUCTURES_H_RPCGEN */
