/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "structures.h"

bool_t
xdr_update_variables (XDR *xdrs, update_variables *objp)
{
	register int32_t *buf;


	if (xdrs->x_op == XDR_ENCODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->update_available))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->update_in_progress))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->updated_from))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->old_version_pid))
				 return FALSE;
		} else {
			IXDR_PUT_LONG(buf, objp->update_available);
			IXDR_PUT_LONG(buf, objp->update_in_progress);
			IXDR_PUT_LONG(buf, objp->updated_from);
			IXDR_PUT_LONG(buf, objp->old_version_pid);
		}
		return TRUE;
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = XDR_INLINE (xdrs, 4 * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			 if (!xdr_int (xdrs, &objp->update_available))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->update_in_progress))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->updated_from))
				 return FALSE;
			 if (!xdr_int (xdrs, &objp->old_version_pid))
				 return FALSE;
		} else {
			objp->update_available = IXDR_GET_LONG(buf);
			objp->update_in_progress = IXDR_GET_LONG(buf);
			objp->updated_from = IXDR_GET_LONG(buf);
			objp->old_version_pid = IXDR_GET_LONG(buf);
		}
	 return TRUE;
	}

	 if (!xdr_int (xdrs, &objp->update_available))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->update_in_progress))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->updated_from))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->old_version_pid))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_container (XDR *xdrs, container *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 50))
		 return FALSE;
	 if (!xdr_float (xdrs, &objp->num_executions))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_container_2 (XDR *xdrs, container_2 *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->name, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_executions))
		 return FALSE;
	return TRUE;
}
